name: Replace version, build docker-container and upload to ghcr.io

on:
   push:
     branches:
       - main

jobs:
  replace_build_upload:
    name: Replace version, build docker-container and upload to ghcr.io
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup Commit Persona
        run: |
          git config user.name "rschardt"
          git config user.email "42609861+rschardt@users.noreply.github.com"

      - name: Install Nix
        uses: cachix/install-nix-action@v27

      - name: Replace version
        run: nix build

      - name: Commit changed file 
        run: |
          cp result/document.txt document.txt
          git add document.txt
          git commit -m "automated commit"
          git push

      - name: Build Docker Container
        run: nix build .\#version-replace-container

      - name: Load Docker Container
        run: docker image load -i result

      - name: Log in to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Upload to ghcr.io
        run: docker push ghcr.io/rschardt/version-replace-container:latest
